[versions]
morphe-patcher = "1.13.0"
smali = "3.0.8"
gson = "2.11.0"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
morphe-patcher = { module = "app.morphe:morphe-patcher", version.ref = "morphe-patcher" }
smali = { module = "com.android.tools.smali:smali-dexlib2", version.ref = "smali" }
